apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: allocation-director-role
rules:
- apiGroups: ["allocation.agones.dev"]
  resources: ["gameserverallocations"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allocate-game-server
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:warcos-director:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: allocation-director-role
  apiGroup: rbac.authorization.k8s.io
