// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserProfile.Models;

#nullable disable

namespace UserProfile.Migrations
{
    [DbContext(typeof(WarcosUserProfileDbContext))]
    partial class WarcosUserProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserProfile.Models.db.Achievement", b =>
                {
                    b.Property<Guid>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RequirementType")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_type");

                    b.Property<int>("RequirementValue")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_value");

                    b.Property<Guid>("RewardItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_item_id");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer")
                        .HasColumnName("reward_type");

                    b.HasKey("AchievementId");

                    b.HasIndex("RewardItemId");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            AchievementId = new Guid("8598de27-d6ce-434e-84b0-1613926ba9c9"),
                            Name = "First Blood",
                            RequirementType = 3,
                            RequirementValue = 1,
                            RewardItemId = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            RewardType = 2
                        },
                        new
                        {
                            AchievementId = new Guid("7d251b3b-b781-44ec-89bf-32bf02cf1380"),
                            Name = "Sharp Shooter",
                            RequirementType = 0,
                            RequirementValue = 10,
                            RewardItemId = new Guid("987f6543-a21b-34d2-c321-765432109876"),
                            RewardType = 2
                        },
                        new
                        {
                            AchievementId = new Guid("9acbb8ee-931c-4e3c-b289-750d40be0c32"),
                            Name = "Unstoppable",
                            RequirementType = 4,
                            RequirementValue = 5,
                            RewardItemId = new Guid("4567d890-1234-56d7-e890-123456789012"),
                            RewardType = 2
                        },
                        new
                        {
                            AchievementId = new Guid("76a5189f-521d-401b-94ae-76f1b4a81ed3"),
                            Name = "Master Tactician",
                            RequirementType = 2,
                            RequirementValue = 50,
                            RewardItemId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            RewardType = 2
                        },
                        new
                        {
                            AchievementId = new Guid("b849e354-9a68-4e00-8a63-d19f15fa8cbc"),
                            Name = "Marathon Runner",
                            RequirementType = 5,
                            RequirementValue = 1440,
                            RewardItemId = new Guid("fedc4321-ba98-76d5-c432-109876543210"),
                            RewardType = 2
                        });
                });

            modelBuilder.Entity("UserProfile.Models.db.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UnrealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ItemId");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = new Guid("123e4567-e89b-12d3-a456-426614174000"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "combat_helmet"
                        },
                        new
                        {
                            ItemId = new Guid("987f6543-a21b-34d2-c321-765432109876"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "high_precision_scope"
                        },
                        new
                        {
                            ItemId = new Guid("4567d890-1234-56d7-e890-123456789012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "armor_piercing_ammo"
                        },
                        new
                        {
                            ItemId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "advanced_grenade"
                        },
                        new
                        {
                            ItemId = new Guid("fedc4321-ba98-76d5-c432-109876543210"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "reinforced_armor"
                        },
                        new
                        {
                            ItemId = new Guid("650edfbf-8e64-4381-ba48-6aa5bc4b978d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "urban_camo_skin"
                        },
                        new
                        {
                            ItemId = new Guid("dade044f-09b6-4e60-b526-62d18844fd2a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "desert_storm_skin"
                        },
                        new
                        {
                            ItemId = new Guid("e941dbdf-9d4a-4130-8855-19432e42dcad"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "jungle_warfare_skin"
                        },
                        new
                        {
                            ItemId = new Guid("b5877b11-5977-4168-b9bf-c4f1d81ae689"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "night_ops_skin"
                        },
                        new
                        {
                            ItemId = new Guid("cae5c7ba-8b41-44ba-86c6-ac13731f8acc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UnrealId = "golden_dragon_skin"
                        });
                });

            modelBuilder.Entity("UserProfile.Models.db.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LevelId"));

                    b.Property<int>("ExperiencePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_points");

                    b.HasKey("LevelId");

                    b.ToTable("levels", (string)null);

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            ExperiencePoints = 1000
                        },
                        new
                        {
                            LevelId = 2,
                            ExperiencePoints = 2000
                        },
                        new
                        {
                            LevelId = 3,
                            ExperiencePoints = 4000
                        },
                        new
                        {
                            LevelId = 4,
                            ExperiencePoints = 7000
                        },
                        new
                        {
                            LevelId = 5,
                            ExperiencePoints = 10000
                        },
                        new
                        {
                            LevelId = 6,
                            ExperiencePoints = 13000
                        },
                        new
                        {
                            LevelId = 7,
                            ExperiencePoints = 18000
                        },
                        new
                        {
                            LevelId = 8,
                            ExperiencePoints = 23000
                        },
                        new
                        {
                            LevelId = 9,
                            ExperiencePoints = 29000
                        },
                        new
                        {
                            LevelId = 10,
                            ExperiencePoints = 35000
                        });
                });

            modelBuilder.Entity("UserProfile.Models.db.LevelReward", b =>
                {
                    b.Property<Guid>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<int?>("LevelId1")
                        .HasColumnType("integer");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_name");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer")
                        .HasColumnName("reward_type");

                    b.HasKey("RewardId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LevelId1")
                        .IsUnique();

                    b.ToTable("level_rewards", (string)null);

                    b.HasData(
                        new
                        {
                            RewardId = new Guid("2e77e8b0-53a4-4c56-893e-f367b8de4b84"),
                            ItemId = new Guid("650edfbf-8e64-4381-ba48-6aa5bc4b978d"),
                            LevelId = 1,
                            RewardName = "Urban Camo Skin",
                            RewardType = 0
                        },
                        new
                        {
                            RewardId = new Guid("1d5f9306-2970-4d8b-a2a8-6cb9b92ed737"),
                            ItemId = new Guid("dade044f-09b6-4e60-b526-62d18844fd2a"),
                            LevelId = 2,
                            RewardName = "Desert Storm Skin",
                            RewardType = 0
                        },
                        new
                        {
                            RewardId = new Guid("46162b0b-68cd-43d3-ada4-f800d2f0aac6"),
                            ItemId = new Guid("e941dbdf-9d4a-4130-8855-19432e42dcad"),
                            LevelId = 3,
                            RewardName = "Jungle Warfare Skin",
                            RewardType = 0
                        },
                        new
                        {
                            RewardId = new Guid("f55e27c4-2321-47ad-9fdc-0d84692e40d1"),
                            ItemId = new Guid("b5877b11-5977-4168-b9bf-c4f1d81ae689"),
                            LevelId = 4,
                            RewardName = "Night Ops Skin",
                            RewardType = 0
                        },
                        new
                        {
                            RewardId = new Guid("838cb5a4-0c27-4152-a40e-e21e4e5c0682"),
                            ItemId = new Guid("cae5c7ba-8b41-44ba-86c6-ac13731f8acc"),
                            LevelId = 5,
                            RewardName = "Golden Dragon Skin",
                            RewardType = 0
                        });
                });

            modelBuilder.Entity("UserProfile.Models.db.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("UserProfile.Models.db.UserLevelReward", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("users_level_rewards", (string)null);
                });

            modelBuilder.Entity("UserProfile.Models.db.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Assists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assists");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("deaths");

                    b.Property<int>("ExperiencePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_points");

                    b.Property<int>("HeadshotKills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("headshot_kills");

                    b.Property<int>("KillStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kill_streak");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kills");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("losses");

                    b.Property<int>("MatchesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("matches_played");

                    b.Property<int>("MeleeKills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("melee_kills");

                    b.Property<TimeSpan>("PlayTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("interval")
                        .HasColumnName("play_time")
                        .HasDefaultValueSql("INTERVAL '0'");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("UserId");

                    b.HasIndex("LevelId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("UserProfile.Models.db.UserProfileStatsHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer")
                        .HasColumnName("experience_points");

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("integer")
                        .HasColumnName("headshot_kills");

                    b.Property<int>("KillStreak")
                        .HasColumnType("integer")
                        .HasColumnName("kill_streak");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("matches_played");

                    b.Property<int>("MeleeKills")
                        .HasColumnType("integer")
                        .HasColumnName("melee_kills");

                    b.Property<TimeSpan>("PlayTime")
                        .HasColumnType("interval")
                        .HasColumnName("play_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("user_profile_stats_history", (string)null);
                });

            modelBuilder.Entity("UserProfile.Models.db.Achievement", b =>
                {
                    b.HasOne("UserProfile.Models.db.Item", "RewardItem")
                        .WithMany("AchievementRewards")
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RewardItem");
                });

            modelBuilder.Entity("UserProfile.Models.db.LevelReward", b =>
                {
                    b.HasOne("UserProfile.Models.db.Item", "Item")
                        .WithMany("LevelRewards")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserProfile.Models.db.Level", "Level")
                        .WithMany("LevelRewards")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserProfile.Models.db.Level", null)
                        .WithOne("Reward")
                        .HasForeignKey("UserProfile.Models.db.LevelReward", "LevelId1");

                    b.Navigation("Item");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("UserProfile.Models.db.UserAchievement", b =>
                {
                    b.HasOne("UserProfile.Models.db.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserProfile.Models.db.UserProfile", "UserProfile")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserProfile.Models.db.UserLevelReward", b =>
                {
                    b.HasOne("UserProfile.Models.db.LevelReward", "LevelReward")
                        .WithMany("UserLevelRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserProfile.Models.db.UserProfile", "UserProfile")
                        .WithMany("UserLevelRewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LevelReward");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserProfile.Models.db.UserProfile", b =>
                {
                    b.HasOne("UserProfile.Models.db.Level", "Level")
                        .WithMany("UserProfiles")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("UserProfile.Models.db.UserProfileStatsHistory", b =>
                {
                    b.HasOne("UserProfile.Models.db.Level", "Level")
                        .WithMany("UserProfileStatsHistories")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserProfile.Models.db.UserProfile", "UserProfile")
                        .WithMany("UserProfileStatsHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserProfile.Models.db.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("UserProfile.Models.db.Item", b =>
                {
                    b.Navigation("AchievementRewards");

                    b.Navigation("LevelRewards");
                });

            modelBuilder.Entity("UserProfile.Models.db.Level", b =>
                {
                    b.Navigation("LevelRewards");

                    b.Navigation("Reward")
                        .IsRequired();

                    b.Navigation("UserProfileStatsHistories");

                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("UserProfile.Models.db.LevelReward", b =>
                {
                    b.Navigation("UserLevelRewards");
                });

            modelBuilder.Entity("UserProfile.Models.db.UserProfile", b =>
                {
                    b.Navigation("UserAchievements");

                    b.Navigation("UserLevelRewards");

                    b.Navigation("UserProfileStatsHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
